### ISSUE TITLE
README scripts failing on Mac

### ISSUE THREAD

**Issue by jacobburrell** [yusufcanb/tlm#10]
For [Ollama](https://ollama.com/) installation instructions on the README

> `curl -fsSL https://ollama.com/install.sh | sh`

Gives this error:
`ERROR This script is intended to run on Linux only.`

For the installation script for tlm:

> `curl -fsSL https://raw.githubusercontent.com/yusufcanb/tlm/main/install.sh | sudo bash -E`

Gives this error: 
`bash: line 39: conditional binary operator expected`

**Comment by jgibbarduk** [comment]
I have the same issue on Mac 14.2.1 (23C71)

**Comment by yusufcanb** [comment]
Just fixed with;

- [https://github.com/yusufcanb/tlm/commit/c34f52e3ac2f176406c12a4bff7a47a566bc97ca](https://github.com/yusufcanb/tlm/commit/c34f52e3ac2f176406c12a4bff7a47a566bc97ca)
- [https://github.com/yusufcanb/tlm/commit/42e0ba5a8233eae26c6fbbb65f9e30e8424f0ea6](https://github.com/yusufcanb/tlm/commit/42e0ba5a8233eae26c6fbbb65f9e30e8424f0ea6)

Sorry for the inconvenience. Thanks giving `tlm` a shot.

**Comment by DogmaF** [comment]
I get the same error message today on Ubuntu 22.04,5 LTS
